In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
data = pd.read_csv('fma-rock-vs-hiphop.csv')
np.random.seed(0)

In [3]:
data

track_id  bit_rate  comments        composer         date_created  \
0           135    256000         1             NaN  2008-11-26 01:43:26   
1           136    256000         1             NaN  2008-11-26 01:43:35   
2           151    192000         0             NaN  2008-11-26 01:44:55   
3           152    192000         0             NaN  2008-11-26 01:44:58   
4           153    256000         0  Arc and Sender  2008-11-26 01:45:00   
...         ...       ...       ...             ...                  ...   
17729    155063    320000         0             NaN  2017-03-24 19:40:43   
17730    155064    320000         0             NaN  2017-03-24 19:40:44   
17731    155065    320000         0             NaN  2017-03-24 19:40:45   
17732    155066    320000         0             NaN  2017-03-24 19:40:47   
17733    155247    320000         0         Fleslit  2017-03-29 01:40:28   

             date_recorded  duration  favorites genre_top          genres  \
0      2008-11-26 00:00:00       837          0      Rock        [45, 58]   
1      2008-11-26 00:00:00       509          0      Rock        [45, 58]   
2                      NaN       192          0      Rock            [25]   
3                      NaN       193          0      Rock            [25]   
4      2008-11-26 00:00:00       405          5      Rock            [26]   
...                    ...       ...        ...       ...             ...   
17729                  NaN       283          3   Hip-Hop       [21, 811]   
17730                  NaN       250          2   Hip-Hop       [21, 811]   
17731                  NaN       219          3   Hip-Hop       [21, 811]   
17732                  NaN       252          6   Hip-Hop       [21, 811]   
17733                  NaN       211          3   Hip-Hop  [21, 539, 811]   

       ... information interest  language_code  \
0      ...         NaN     2484             en   
1      ...         NaN     1948             en   
2      ...         NaN      701             en   
3      ...         NaN      637             en   
4      ...         NaN      354             en   
...    ...         ...      ...            ...   
17729  ...         NaN     1283            NaN   
17730  ...         NaN     1077            NaN   
17731  ...         NaN     1340            NaN   
17732  ...         NaN     2065            NaN   
17733  ...         NaN     1379            NaN   

                                                 license listens  lyricist  \
0      Attribution-NonCommercial-ShareAlike 3.0 Inter...    1832       NaN   
1      Attribution-NonCommercial-ShareAlike 3.0 Inter...    1498       NaN   
2      Attribution-NonCommercial-ShareAlike 3.0 Inter...     148       NaN   
3      Attribution-NonCommercial-ShareAlike 3.0 Inter...      98       NaN   
4      Attribution-NonCommercial-NoDerivatives (aka M...     424       NaN   
...                                                  ...     ...       ...   
17729                                        Attribution    1050       NaN   
17730                                        Attribution     858       NaN   
17731                                        Attribution    1142       NaN   
17732                                        Attribution    1474       NaN   
17733                                        Attribution    1025       NaN   

      number  publisher                                               tags  \
0          0        NaN                                                 []   
1          0        NaN                                                 []   
2          4        NaN                                                 []   
3         11        NaN                                                 []   
4          2        NaN                                                 []   
...      ...        ...                                                ...   
17729      4        NaN  ['old school beats', '2017 free instrumentals'...   
17730  

In [4]:
data.columns

Index(['track_id', 'bit_rate', 'comments', 'composer', 'date_created',
       'date_recorded', 'duration', 'favorites', 'genre_top', 'genres',
       'genres_all', 'information', 'interest', 'language_code', 'license',
       'listens', 'lyricist', 'number', 'publisher', 'tags', 'title'],
      dtype='object')

In [5]:
missing_vals_count = data.isnull().sum()

In [6]:
missing_vals_count

track_id             0
bit_rate             0
comments             0
composer         17568
date_created         0
date_recorded    15836
duration             0
favorites            0
genre_top            0
genres               0
genres_all           0
information      17252
interest             0
language_code    13645
license             20
listens              0
lyricist         17681
number               0
publisher        17682
tags                 0
title                0
dtype: int64

In [7]:
total_cells = np.product(data.shape)
total_missing = missing_vals_count.sum()

percent_missing = total_missing / total_cells * 100
print(percent_missing, total_cells, total_missing)

26.76698512945271 372414 99684


In [8]:
data_clear = data.dropna(axis=1)
data_clear.head()

track_id  bit_rate  comments         date_created  duration  favorites  \
0       135    256000         1  2008-11-26 01:43:26       837          0   
1       136    256000         1  2008-11-26 01:43:35       509          0   
2       151    192000         0  2008-11-26 01:44:55       192          0   
3       152    192000         0  2008-11-26 01:44:58       193          0   
4       153    256000         0  2008-11-26 01:45:00       405          5   

  genre_top    genres    genres_all  interest  listens  number tags  \
0      Rock  [45, 58]  [58, 12, 45]      2484     1832       0   []   
1      Rock  [45, 58]  [58, 12, 45]      1948     1498       0   []   
2      Rock      [25]      [25, 12]       701      148       4   []   
3      Rock      [25]      [25, 12]       637       98      11   []   
4      Rock      [26]      [26, 12]       354      424       2   []   

                        title  
0                Father's Day  
1  Peel Back The Mountain Sky  
2                 Untitled 04  
3                 Untitled 11  
4          Hundred-Year Flood

In [9]:
print("Columns in original dataset: %d \n" % data.shape[1])
print("Columns with na's dropped: %d" % data_clear.shape[1])

Columns in original dataset: 21 

Columns with na's dropped: 14


In [10]:
data_clear = data_clear.fillna(method='bfill', axis=0).fillna(0)

In [11]:
data_clear

track_id  bit_rate  comments         date_created  duration  favorites  \
0           135    256000         1  2008-11-26 01:43:26       837          0   
1           136    256000         1  2008-11-26 01:43:35       509          0   
2           151    192000         0  2008-11-26 01:44:55       192          0   
3           152    192000         0  2008-11-26 01:44:58       193          0   
4           153    256000         0  2008-11-26 01:45:00       405          5   
...         ...       ...       ...                  ...       ...        ...   
17729    155063    320000         0  2017-03-24 19:40:43       283          3   
17730    155064    320000         0  2017-03-24 19:40:44       250          2   
17731    155065    320000         0  2017-03-24 19:40:45       219          3   
17732    155066    320000         0  2017-03-24 19:40:47       252          6   
17733    155247    320000         0  2017-03-29 01:40:28       211          3   

      genre_top          genres      genres_all  interest  listens  number  \
0          Rock        [45, 58]    [58, 12, 45]      2484     1832       0   
1          Rock        [45, 58]    [58, 12, 45]      1948     1498       0   
2          Rock            [25]        [25, 12]       701      148       4   
3          Rock            [25]        [25, 12]       637       98      11   
4          Rock            [26]        [26, 12]       354      424       2   
...         ...             ...             ...       ...      ...     ...   
17729   Hip-Hop       [21, 811]       [811, 21]      1283     1050       4   
17730   Hip-Hop       [21, 811]       [811, 21]      1077      858       2   
17731   Hip-Hop       [21, 811]       [811, 21]      1340     1142       1   
17732   Hip-Hop       [21, 811]       [811, 21]      2065     1474       3   
17733   Hip-Hop  [21, 539, 811]  [811, 539, 21]      1379     1025       0   

                                                    tags  \
0                                                     []   
1                                                     []   
2                                                     []   
3                                                     []   
4                                                     []   
...                                                  ...   
17729  ['old school beats', '2017 free instrumentals'...   
17730  ['old school beats', '2017 free instrumentals'...   
17731  ['old school beats', '2017 free instrumentals'...   
17732  ['old school beats', '2017 free instrumentals'...   
17733  ['instrumental trap beat', 'love', 'instrument...   

                            title  
0                    Father's Day  
1      Peel Back The Mountain Sky  
2                     Untitled 04  
3                     Untitled 11  
4              Hundred-Year Flood  
...                           ...  
17729                     Been On  
17730                     Send Me  
17731                The Question  
17732                         Roy  
17733             Love In The Sky  

[17734 rows x 14 columns]

In [12]:
from scipy import stats
from sklearn.preprocessing import MinMaxScaler

In [13]:
data_for_prediction = data_clear.drop(labels=['track_id', 'date_created', 'genres', 'genres_all', \
                                              'tags', 'title', 'listens'], axis=1)

In [14]:
data_for_prediction

bit_rate  comments  duration  favorites genre_top  interest  number
0        256000         1       837          0      Rock      2484       0
1        256000         1       509          0      Rock      1948       0
2        192000         0       192          0      Rock       701       4
3        192000         0       193          0      Rock       637      11
4        256000         0       405          5      Rock       354       2
...         ...       ...       ...        ...       ...       ...     ...
17729    320000         0       283          3   Hip-Hop      1283       4
17730    320000         0       250          2   Hip-Hop      1077       2
17731    320000         0       219          3   Hip-Hop      1340       1
17732    320000         0       252          6   Hip-Hop      2065       3
17733    320000         0       211          3   Hip-Hop      1379       0

[17734 rows x 7 columns]

In [15]:
data_for_prediction.corr()

bit_rate  comments  duration  favorites  interest    number
bit_rate   1.000000 -0.002230  0.023969  -0.001800 -0.022650  0.074227
comments  -0.002230  1.000000  0.023166   0.630017  0.417699 -0.017872
duration   0.023969  0.023166  1.000000   0.008260 -0.005068 -0.039274
favorites -0.001800  0.630017  0.008260   1.000000  0.667735 -0.038298
interest  -0.022650  0.417699 -0.005068   0.667735  1.000000 -0.017139
number     0.074227 -0.017872 -0.039274  -0.038298 -0.017139  1.000000

**Seems like I should get rid of interest or listens column because of 0.9455 positive correlation, but let me try to use them for prediction. If prediction fails, then I will see how much effect it fill cause if I drop one of them**

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
y = data_for_prediction['genre_top']
X = data_for_prediction.drop(labels=['genre_top'], axis=1)

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [48]:
from sklearn.preprocessing import StandardScaler

In [49]:
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [50]:
from sklearn.decomposition import PCA

In [51]:
pca = PCA(n_components=2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_

In [52]:
X_train

array([[ 1.98940976,  0.66899986],
       [ 0.11973058, -0.31134748],
       [ 0.0065117 , -0.36633519],
       ...,
       [-0.24238135,  0.61867681],
       [-0.20788034, -0.75686693],
       [-0.20657461,  0.25723847]])

In [53]:
X_test

array([[ 0.66466937,  0.22395213],
       [-0.2565371 ,  0.08426185],
       [-0.27823691,  0.69207016],
       ...,
       [-0.209966  ,  0.48994501],
       [-0.0036425 ,  1.14722882],
       [-0.06249709, -0.34190732]])

In [54]:
explained_variance

array([0.36571077, 0.17901606])

In [55]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [100]:
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression()

In [101]:
y_pred = classifier.predict(X_test)

In [102]:
y_pred

array(['Rock', 'Rock', 'Rock', ..., 'Rock', 'Rock', 'Rock'], dtype=object)

In [103]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [104]:
cm = confusion_matrix(y_test, y_pred) 
acc = accuracy_score(y_test, y_pred)
result = classification_report(y_test, y_pred)

In [109]:
print(cm)

[[  24  725]
 [  18 2780]]


In [106]:
acc

0.7905272060896532

In [108]:
print(result)

              precision    recall  f1-score   support

     Hip-Hop       0.57      0.03      0.06       749
        Rock       0.79      0.99      0.88      2798

    accuracy                           0.79      3547
   macro avg       0.68      0.51      0.47      3547
weighted avg       0.75      0.79      0.71      3547



In [57]:
train_y = []
test_y = []
for i in y_train:
    if i == 'Rock':
        train_y.append(0)
    else:
        train_y.append(1)
for j in y_test:
    if i == 'Rock':
        test_y.append(0)
    else:
        test_y.append(1)